olateste,teste.maplink.com.br
default["apache2-axiodis"]["sites"]["momo"] = { "port_http" => 80, "port_https" => 443, "servername" => "momo-axiodis.maplink.global", "app_workername" => "axiodisMOMOappWorker", "cal_workername" => "axiodisMOMOcalWorker" }
default["apache2-axiodis"]["sites"]["terra"] = { "port_http" => 80, "port_https" => 443, "servername" => "terra-axiodis.maplink.global", "app_workername" => "axiodisTERRAappWorker", "cal_workername" => "axiodisTERRAcalWorker" }
default["apache2-axiodis"]["sites"]["tete"] = { "port_http" => 80, "port_https" => 443, "servername" => "tete-axiodis.maplink.global", "app_workername" => "axiodisTETEappWorker", "cal_workername" => "axiodisTETEcalWorker" }
default["apache2-axiodis"]["sites"]["asds"] = { "port_http" => 80, "port_https" => 443, "servername" => "asds-axiodis.maplink.global", "app_workername" => "axiodisASDSappWorker", "cal_workername" => "axiodisASDScalWorker" }
default["apache2-axiodis"]["sites"]["dss"] = { "port_http" => 80, "port_https" => 443, "servername" => "dss-axiodis.maplink.global", "app_workername" => "axiodisDSSappWorker", "cal_workername" => "axiodisDSScalWorker" }
default["apache2-axiodis"]["sites"]["ddd"] = { "port_http" => 80, "port_https" => 443, "servername" => "ddd-axiodis.maplink.global", "app_workername" => "axiodisDDDappWorker", "cal_workername" => "axiodisDDDcalWorker" }
default["apache2-axiodis"]["sites"]["ttt"] = { "port_http" => 80, "port_https" => 443, "servername" => "ttt-axiodis.maplink.global", "app_workername" => "axiodisTTTappWorker", "cal_workername" => "axiodisTTTcalWorker" }
default["apache2-axiodis"]["sites"]["123"] = { "port_http" => 80, "port_https" => 443, "servername" => "123-axiodis.maplink.global", "app_workername" => "axiodis123appWorker", "cal_workername" => "axiodis123calWorker" }
default["apache2-axiodis"]["sites"]["345"] = { "port_http" => 80, "port_https" => 443, "servername" => "345-axiodis.maplink.global", "app_workername" => "axiodis345appWorker", "cal_workername" => "axiodis345calWorker" }
default["apache2-axiodis"]["sites"]["total"] = { "port_http" => 80, "port_https" => 443, "servername" => "total-axiodis.maplink.global", "app_workername" => "axiodisTOTALappWorker", "cal_workername" => "axiodisTOTALcalWorker" }
default["apache2-axiodis"]["sites"]["rrr"] = { "port_http" => 80, "port_https" => 443, "servername" => "rrr-axiodis.maplink.global", "app_workername" => "axiodisRRRappWorker", "cal_workername" => "axiodisRRRcalWorker" }
default["apache2-axiodis"]["sites"]["555"] = { "port_http" => 80, "port_https" => 443, "servername" => "555-axiodis.maplink.global", "app_workername" => "axiodis555appWorker", "cal_workername" => "axiodis555calWorker" }
default["apache2-axiodis"]["sites"]["terere"] = { "port_http" => 80, "port_https" => 443, "servername" => "terere-axiodis.maplink.global", "app_workername" => "axiodisTEREREappWorker", "cal_workername" => "axiodisTEREREcalWorker" }
default["apache2-axiodis"]["sites"]["canastra"] = { "port_http" => 80, "port_https" => 443, "servername" => "canastra-axiodis.maplink.global", "app_workername" => "axiodisCANASTRAappWorker", "cal_workername" => "axiodisCANASTRAcalWorker" }
